// Code generated by go-swagger; DO NOT EDIT.

package bulk_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/GoDieNow/TFT_Code/services/billing/models"
)

// ListBillRunsOKCode is the HTTP code returned for type ListBillRunsOK
const ListBillRunsOKCode int = 200

/*ListBillRunsOK Description of a successfully operation

swagger:response listBillRunsOK
*/
type ListBillRunsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.BillRunList `json:"body,omitempty"`
}

// NewListBillRunsOK creates ListBillRunsOK with default headers values
func NewListBillRunsOK() *ListBillRunsOK {

	return &ListBillRunsOK{}
}

// WithPayload adds the payload to the list bill runs o k response
func (o *ListBillRunsOK) WithPayload(payload []*models.BillRunList) *ListBillRunsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list bill runs o k response
func (o *ListBillRunsOK) SetPayload(payload []*models.BillRunList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListBillRunsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.BillRunList, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListBillRunsInternalServerErrorCode is the HTTP code returned for type ListBillRunsInternalServerError
const ListBillRunsInternalServerErrorCode int = 500

/*ListBillRunsInternalServerError Something unexpected happend, error raised

swagger:response listBillRunsInternalServerError
*/
type ListBillRunsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewListBillRunsInternalServerError creates ListBillRunsInternalServerError with default headers values
func NewListBillRunsInternalServerError() *ListBillRunsInternalServerError {

	return &ListBillRunsInternalServerError{}
}

// WithPayload adds the payload to the list bill runs internal server error response
func (o *ListBillRunsInternalServerError) WithPayload(payload *models.ErrorResponse) *ListBillRunsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list bill runs internal server error response
func (o *ListBillRunsInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListBillRunsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
