// Code generated by go-swagger; DO NOT EDIT.

package account_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DisableAccountHandlerFunc turns a function with the right signature into a disable account handler
type DisableAccountHandlerFunc func(DisableAccountParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DisableAccountHandlerFunc) Handle(params DisableAccountParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DisableAccountHandler interface for that can handle valid disable account params
type DisableAccountHandler interface {
	Handle(DisableAccountParams, interface{}) middleware.Responder
}

// NewDisableAccount creates a new http.Handler for the disable account operation
func NewDisableAccount(ctx *middleware.Context, handler DisableAccountHandler) *DisableAccount {
	return &DisableAccount{Context: ctx, Handler: handler}
}

/*DisableAccount swagger:route POST /account/disable/{id} accountManagement disableAccount

Disables the account with the id provided in the system

*/
type DisableAccount struct {
	Context *middleware.Context
	Handler DisableAccountHandler
}

func (o *DisableAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDisableAccountParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
