// Code generated by go-swagger; DO NOT EDIT.

package account_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAccountStatusHandlerFunc turns a function with the right signature into a get account status handler
type GetAccountStatusHandlerFunc func(GetAccountStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAccountStatusHandlerFunc) Handle(params GetAccountStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAccountStatusHandler interface for that can handle valid get account status params
type GetAccountStatusHandler interface {
	Handle(GetAccountStatusParams, interface{}) middleware.Responder
}

// NewGetAccountStatus creates a new http.Handler for the get account status operation
func NewGetAccountStatus(ctx *middleware.Context, handler GetAccountStatusHandler) *GetAccountStatus {
	return &GetAccountStatus{Context: ctx, Handler: handler}
}

/*GetAccountStatus swagger:route GET /account/status/{id} accountManagement getAccountStatus

Basic status of the account with the id provided in the system

*/
type GetAccountStatus struct {
	Context *middleware.Context
	Handler GetAccountStatusHandler
}

func (o *GetAccountStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAccountStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
