// Code generated by go-swagger; DO NOT EDIT.

package cycle_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/GoDieNow/TFT_Code/services/planmanager/models"
)

// NewCreateCycleParams creates a new CreateCycleParams object
// no default values defined in spec.
func NewCreateCycleParams() CreateCycleParams {

	return CreateCycleParams{}
}

// CreateCycleParams contains all the bound params for the create cycle operation
// typically these are obtained from a http.Request
//
// swagger:parameters createCycle
type CreateCycleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Cycle to be added
	  In: body
	*/
	Cycle *models.Cycle
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateCycleParams() beforehand.
func (o *CreateCycleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Cycle
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("cycle", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Cycle = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
