// Code generated by go-swagger; DO NOT EDIT.

package cycle_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateCycleHandlerFunc turns a function with the right signature into a create cycle handler
type CreateCycleHandlerFunc func(CreateCycleParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateCycleHandlerFunc) Handle(params CreateCycleParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateCycleHandler interface for that can handle valid create cycle params
type CreateCycleHandler interface {
	Handle(CreateCycleParams, interface{}) middleware.Responder
}

// NewCreateCycle creates a new http.Handler for the create cycle operation
func NewCreateCycle(ctx *middleware.Context, handler CreateCycleHandler) *CreateCycle {
	return &CreateCycle{Context: ctx, Handler: handler}
}

/*CreateCycle swagger:route POST /cycle cycleManagement createCycle

Create a plan

Creates a new cycle

*/
type CreateCycle struct {
	Context *middleware.Context
	Handler CreateCycleHandler
}

func (o *CreateCycle) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateCycleParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
