// Code generated by go-swagger; DO NOT EDIT.

package cycle_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListCyclesHandlerFunc turns a function with the right signature into a list cycles handler
type ListCyclesHandlerFunc func(ListCyclesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListCyclesHandlerFunc) Handle(params ListCyclesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListCyclesHandler interface for that can handle valid list cycles params
type ListCyclesHandler interface {
	Handle(ListCyclesParams, interface{}) middleware.Responder
}

// NewListCycles creates a new http.Handler for the list cycles operation
func NewListCycles(ctx *middleware.Context, handler ListCyclesHandler) *ListCycles {
	return &ListCycles{Context: ctx, Handler: handler}
}

/*ListCycles swagger:route GET /cycle cycleManagement listCycles

List all cycles

lists all cycles

*/
type ListCycles struct {
	Context *middleware.Context
	Handler ListCyclesHandler
}

func (o *ListCycles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListCyclesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
