// Code generated by go-swagger; DO NOT EDIT.

package event_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/GoDieNow/TFT_Code/services/eventsengine/models"
)

// AddEventCreatedCode is the HTTP code returned for type AddEventCreated
const AddEventCreatedCode int = 201

/*AddEventCreated Item added successfully

swagger:response addEventCreated
*/
type AddEventCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ItemCreatedResponse `json:"body,omitempty"`
}

// NewAddEventCreated creates AddEventCreated with default headers values
func NewAddEventCreated() *AddEventCreated {

	return &AddEventCreated{}
}

// WithPayload adds the payload to the add event created response
func (o *AddEventCreated) WithPayload(payload *models.ItemCreatedResponse) *AddEventCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add event created response
func (o *AddEventCreated) SetPayload(payload *models.ItemCreatedResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddEventCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddEventBadRequestCode is the HTTP code returned for type AddEventBadRequest
const AddEventBadRequestCode int = 400

/*AddEventBadRequest Invalid input, object invalid

swagger:response addEventBadRequest
*/
type AddEventBadRequest struct {
}

// NewAddEventBadRequest creates AddEventBadRequest with default headers values
func NewAddEventBadRequest() *AddEventBadRequest {

	return &AddEventBadRequest{}
}

// WriteResponse to the client
func (o *AddEventBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddEventInternalServerErrorCode is the HTTP code returned for type AddEventInternalServerError
const AddEventInternalServerErrorCode int = 500

/*AddEventInternalServerError Something unexpected happend, error raised

swagger:response addEventInternalServerError
*/
type AddEventInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewAddEventInternalServerError creates AddEventInternalServerError with default headers values
func NewAddEventInternalServerError() *AddEventInternalServerError {

	return &AddEventInternalServerError{}
}

// WithPayload adds the payload to the add event internal server error response
func (o *AddEventInternalServerError) WithPayload(payload *models.ErrorResponse) *AddEventInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add event internal server error response
func (o *AddEventInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddEventInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
