// Code generated by go-swagger; DO NOT EDIT.

package invoice_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GenerateInvoiceForCustomerHandlerFunc turns a function with the right signature into a generate invoice for customer handler
type GenerateInvoiceForCustomerHandlerFunc func(GenerateInvoiceForCustomerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GenerateInvoiceForCustomerHandlerFunc) Handle(params GenerateInvoiceForCustomerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GenerateInvoiceForCustomerHandler interface for that can handle valid generate invoice for customer params
type GenerateInvoiceForCustomerHandler interface {
	Handle(GenerateInvoiceForCustomerParams, interface{}) middleware.Responder
}

// NewGenerateInvoiceForCustomer creates a new http.Handler for the generate invoice for customer operation
func NewGenerateInvoiceForCustomer(ctx *middleware.Context, handler GenerateInvoiceForCustomerHandler) *GenerateInvoiceForCustomer {
	return &GenerateInvoiceForCustomer{Context: ctx, Handler: handler}
}

/*GenerateInvoiceForCustomer swagger:route POST /invoice/customer/{id} invoiceManagement generateInvoiceForCustomer

Generate invoice for the provided customer for the provided time window or last period

*/
type GenerateInvoiceForCustomer struct {
	Context *middleware.Context
	Handler GenerateInvoiceForCustomerHandler
}

func (o *GenerateInvoiceForCustomer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGenerateInvoiceForCustomerParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
