// Code generated by go-swagger; DO NOT EDIT.

package invoice_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetInvoicesByCustomerHandlerFunc turns a function with the right signature into a get invoices by customer handler
type GetInvoicesByCustomerHandlerFunc func(GetInvoicesByCustomerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetInvoicesByCustomerHandlerFunc) Handle(params GetInvoicesByCustomerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetInvoicesByCustomerHandler interface for that can handle valid get invoices by customer params
type GetInvoicesByCustomerHandler interface {
	Handle(GetInvoicesByCustomerParams, interface{}) middleware.Responder
}

// NewGetInvoicesByCustomer creates a new http.Handler for the get invoices by customer operation
func NewGetInvoicesByCustomer(ctx *middleware.Context, handler GetInvoicesByCustomerHandler) *GetInvoicesByCustomer {
	return &GetInvoicesByCustomer{Context: ctx, Handler: handler}
}

/*GetInvoicesByCustomer swagger:route GET /invoice/customer/{id} invoiceManagement getInvoicesByCustomer

Retrieve invoices by customer id

*/
type GetInvoicesByCustomer struct {
	Context *middleware.Context
	Handler GetInvoicesByCustomerHandler
}

func (o *GetInvoicesByCustomer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetInvoicesByCustomerParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
