// Code generated by go-swagger; DO NOT EDIT.

package invoice_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/GoDieNow/TFT_Code/services/billing/models"
)

// GetInvoiceOKCode is the HTTP code returned for type GetInvoiceOK
const GetInvoiceOKCode int = 200

/*GetInvoiceOK Description of a successfully operation

swagger:response getInvoiceOK
*/
type GetInvoiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Invoice `json:"body,omitempty"`
}

// NewGetInvoiceOK creates GetInvoiceOK with default headers values
func NewGetInvoiceOK() *GetInvoiceOK {

	return &GetInvoiceOK{}
}

// WithPayload adds the payload to the get invoice o k response
func (o *GetInvoiceOK) WithPayload(payload *models.Invoice) *GetInvoiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get invoice o k response
func (o *GetInvoiceOK) SetPayload(payload *models.Invoice) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInvoiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetInvoiceNotFoundCode is the HTTP code returned for type GetInvoiceNotFound
const GetInvoiceNotFoundCode int = 404

/*GetInvoiceNotFound The invoice id provided doesn't exist

swagger:response getInvoiceNotFound
*/
type GetInvoiceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetInvoiceNotFound creates GetInvoiceNotFound with default headers values
func NewGetInvoiceNotFound() *GetInvoiceNotFound {

	return &GetInvoiceNotFound{}
}

// WithPayload adds the payload to the get invoice not found response
func (o *GetInvoiceNotFound) WithPayload(payload *models.ErrorResponse) *GetInvoiceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get invoice not found response
func (o *GetInvoiceNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInvoiceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetInvoiceInternalServerErrorCode is the HTTP code returned for type GetInvoiceInternalServerError
const GetInvoiceInternalServerErrorCode int = 500

/*GetInvoiceInternalServerError Something unexpected happend, error raised

swagger:response getInvoiceInternalServerError
*/
type GetInvoiceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetInvoiceInternalServerError creates GetInvoiceInternalServerError with default headers values
func NewGetInvoiceInternalServerError() *GetInvoiceInternalServerError {

	return &GetInvoiceInternalServerError{}
}

// WithPayload adds the payload to the get invoice internal server error response
func (o *GetInvoiceInternalServerError) WithPayload(payload *models.ErrorResponse) *GetInvoiceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get invoice internal server error response
func (o *GetInvoiceInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInvoiceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
