// Code generated by go-swagger; DO NOT EDIT.

package invoice_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListCustomerInvoicesHandlerFunc turns a function with the right signature into a list customer invoices handler
type ListCustomerInvoicesHandlerFunc func(ListCustomerInvoicesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListCustomerInvoicesHandlerFunc) Handle(params ListCustomerInvoicesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListCustomerInvoicesHandler interface for that can handle valid list customer invoices params
type ListCustomerInvoicesHandler interface {
	Handle(ListCustomerInvoicesParams, interface{}) middleware.Responder
}

// NewListCustomerInvoices creates a new http.Handler for the list customer invoices operation
func NewListCustomerInvoices(ctx *middleware.Context, handler ListCustomerInvoicesHandler) *ListCustomerInvoices {
	return &ListCustomerInvoices{Context: ctx, Handler: handler}
}

/*ListCustomerInvoices swagger:route GET /invoice/customer invoiceManagement listCustomerInvoices

Retrieve customers' invoices

*/
type ListCustomerInvoices struct {
	Context *middleware.Context
	Handler ListCustomerInvoicesHandler
}

func (o *ListCustomerInvoices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListCustomerInvoicesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
