// Code generated by go-swagger; DO NOT EDIT.

package trigger_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the trigger management client
type API interface {
	/*
	   ExecTransformation transformations of u d r to c d r task trigger*/
	ExecTransformation(ctx context.Context, params *ExecTransformationParams) (*ExecTransformationOK, error)
}

// New creates a new trigger management API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for trigger management API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
ExecTransformation transformations of u d r to c d r task trigger
*/
func (a *Client) ExecTransformation(ctx context.Context, params *ExecTransformationParams) (*ExecTransformationOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "execTransformation",
		Method:             "GET",
		PathPattern:        "/trigger/transform",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ExecTransformationReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ExecTransformationOK), nil

}
