// Code generated by go-swagger; DO NOT EDIT.

package customer_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListCustomersParams creates a new ListCustomersParams object
// with the default values initialized.
func NewListCustomersParams() *ListCustomersParams {

	return &ListCustomersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListCustomersParamsWithTimeout creates a new ListCustomersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListCustomersParamsWithTimeout(timeout time.Duration) *ListCustomersParams {

	return &ListCustomersParams{

		timeout: timeout,
	}
}

// NewListCustomersParamsWithContext creates a new ListCustomersParams object
// with the default values initialized, and the ability to set a context for a request
func NewListCustomersParamsWithContext(ctx context.Context) *ListCustomersParams {

	return &ListCustomersParams{

		Context: ctx,
	}
}

// NewListCustomersParamsWithHTTPClient creates a new ListCustomersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListCustomersParamsWithHTTPClient(client *http.Client) *ListCustomersParams {

	return &ListCustomersParams{
		HTTPClient: client,
	}
}

/*ListCustomersParams contains all the parameters to send to the API endpoint
for the list customers operation typically these are written to a http.Request
*/
type ListCustomersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list customers params
func (o *ListCustomersParams) WithTimeout(timeout time.Duration) *ListCustomersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list customers params
func (o *ListCustomersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list customers params
func (o *ListCustomersParams) WithContext(ctx context.Context) *ListCustomersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list customers params
func (o *ListCustomersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list customers params
func (o *ListCustomersParams) WithHTTPClient(client *http.Client) *ListCustomersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list customers params
func (o *ListCustomersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListCustomersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
