// Code generated by go-swagger; DO NOT EDIT.

package cycle_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/GoDieNow/TFT_Code/services/planmanager/models"
)

// ListCyclesReader is a Reader for the ListCycles structure.
type ListCyclesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListCyclesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListCyclesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListCyclesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListCyclesOK creates a ListCyclesOK with default headers values
func NewListCyclesOK() *ListCyclesOK {
	return &ListCyclesOK{}
}

/*ListCyclesOK handles this case with default header values.

list of cycles returned
*/
type ListCyclesOK struct {
	Payload []*models.Cycle
}

func (o *ListCyclesOK) Error() string {
	return fmt.Sprintf("[GET /cycle][%d] listCyclesOK  %+v", 200, o.Payload)
}

func (o *ListCyclesOK) GetPayload() []*models.Cycle {
	return o.Payload
}

func (o *ListCyclesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListCyclesInternalServerError creates a ListCyclesInternalServerError with default headers values
func NewListCyclesInternalServerError() *ListCyclesInternalServerError {
	return &ListCyclesInternalServerError{}
}

/*ListCyclesInternalServerError handles this case with default header values.

unexpected error
*/
type ListCyclesInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *ListCyclesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /cycle][%d] listCyclesInternalServerError  %+v", 500, o.Payload)
}

func (o *ListCyclesInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListCyclesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
