// Code generated by go-swagger; DO NOT EDIT.

package plan_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreatePlanHandlerFunc turns a function with the right signature into a create plan handler
type CreatePlanHandlerFunc func(CreatePlanParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreatePlanHandlerFunc) Handle(params CreatePlanParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreatePlanHandler interface for that can handle valid create plan params
type CreatePlanHandler interface {
	Handle(CreatePlanParams, interface{}) middleware.Responder
}

// NewCreatePlan creates a new http.Handler for the create plan operation
func NewCreatePlan(ctx *middleware.Context, handler CreatePlanHandler) *CreatePlan {
	return &CreatePlan{Context: ctx, Handler: handler}
}

/*CreatePlan swagger:route POST /plan planManagement createPlan

Create a plan

Creates a new plan

*/
type CreatePlan struct {
	Context *middleware.Context
	Handler CreatePlanHandler
}

func (o *CreatePlan) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreatePlanParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
