// Code generated by go-swagger; DO NOT EDIT.

package plan_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/GoDieNow/TFT_Code/services/planmanager/models"
)

// UpdatePlanOKCode is the HTTP code returned for type UpdatePlanOK
const UpdatePlanOKCode int = 200

/*UpdatePlanOK updated plan

swagger:response updatePlanOK
*/
type UpdatePlanOK struct {

	/*
	  In: Body
	*/
	Payload *models.Plan `json:"body,omitempty"`
}

// NewUpdatePlanOK creates UpdatePlanOK with default headers values
func NewUpdatePlanOK() *UpdatePlanOK {

	return &UpdatePlanOK{}
}

// WithPayload adds the payload to the update plan o k response
func (o *UpdatePlanOK) WithPayload(payload *models.Plan) *UpdatePlanOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update plan o k response
func (o *UpdatePlanOK) SetPayload(payload *models.Plan) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdatePlanOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdatePlanNotFoundCode is the HTTP code returned for type UpdatePlanNotFound
const UpdatePlanNotFoundCode int = 404

/*UpdatePlanNotFound plan with planid not found

swagger:response updatePlanNotFound
*/
type UpdatePlanNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdatePlanNotFound creates UpdatePlanNotFound with default headers values
func NewUpdatePlanNotFound() *UpdatePlanNotFound {

	return &UpdatePlanNotFound{}
}

// WithPayload adds the payload to the update plan not found response
func (o *UpdatePlanNotFound) WithPayload(payload *models.ErrorResponse) *UpdatePlanNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update plan not found response
func (o *UpdatePlanNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdatePlanNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdatePlanInternalServerErrorCode is the HTTP code returned for type UpdatePlanInternalServerError
const UpdatePlanInternalServerErrorCode int = 500

/*UpdatePlanInternalServerError unexpected error

swagger:response updatePlanInternalServerError
*/
type UpdatePlanInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdatePlanInternalServerError creates UpdatePlanInternalServerError with default headers values
func NewUpdatePlanInternalServerError() *UpdatePlanInternalServerError {

	return &UpdatePlanInternalServerError{}
}

// WithPayload adds the payload to the update plan internal server error response
func (o *UpdatePlanInternalServerError) WithPayload(payload *models.ErrorResponse) *UpdatePlanInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update plan internal server error response
func (o *UpdatePlanInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdatePlanInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
