// Code generated by go-swagger; DO NOT EDIT.

package sku_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSkuParams creates a new GetSkuParams object
// with the default values initialized.
func NewGetSkuParams() *GetSkuParams {
	var ()
	return &GetSkuParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSkuParamsWithTimeout creates a new GetSkuParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSkuParamsWithTimeout(timeout time.Duration) *GetSkuParams {
	var ()
	return &GetSkuParams{

		timeout: timeout,
	}
}

// NewGetSkuParamsWithContext creates a new GetSkuParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSkuParamsWithContext(ctx context.Context) *GetSkuParams {
	var ()
	return &GetSkuParams{

		Context: ctx,
	}
}

// NewGetSkuParamsWithHTTPClient creates a new GetSkuParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSkuParamsWithHTTPClient(client *http.Client) *GetSkuParams {
	var ()
	return &GetSkuParams{
		HTTPClient: client,
	}
}

/*GetSkuParams contains all the parameters to send to the API endpoint
for the get sku operation typically these are written to a http.Request
*/
type GetSkuParams struct {

	/*ID
	  Id of sku to be obtained

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sku params
func (o *GetSkuParams) WithTimeout(timeout time.Duration) *GetSkuParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sku params
func (o *GetSkuParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sku params
func (o *GetSkuParams) WithContext(ctx context.Context) *GetSkuParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sku params
func (o *GetSkuParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sku params
func (o *GetSkuParams) WithHTTPClient(client *http.Client) *GetSkuParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sku params
func (o *GetSkuParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get sku params
func (o *GetSkuParams) WithID(id string) *GetSkuParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get sku params
func (o *GetSkuParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSkuParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
