// Code generated by go-swagger; DO NOT EDIT.

package event_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStateParams creates a new GetStateParams object
// with the default values initialized.
func NewGetStateParams() *GetStateParams {
	var ()
	return &GetStateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStateParamsWithTimeout creates a new GetStateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStateParamsWithTimeout(timeout time.Duration) *GetStateParams {
	var ()
	return &GetStateParams{

		timeout: timeout,
	}
}

// NewGetStateParamsWithContext creates a new GetStateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStateParamsWithContext(ctx context.Context) *GetStateParams {
	var ()
	return &GetStateParams{

		Context: ctx,
	}
}

// NewGetStateParamsWithHTTPClient creates a new GetStateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStateParamsWithHTTPClient(client *http.Client) *GetStateParams {
	var ()
	return &GetStateParams{
		HTTPClient: client,
	}
}

/*GetStateParams contains all the parameters to send to the API endpoint
for the get state operation typically these are written to a http.Request
*/
type GetStateParams struct {

	/*Account
	  Id of the account to be checked

	*/
	Account string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get state params
func (o *GetStateParams) WithTimeout(timeout time.Duration) *GetStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get state params
func (o *GetStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get state params
func (o *GetStateParams) WithContext(ctx context.Context) *GetStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get state params
func (o *GetStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get state params
func (o *GetStateParams) WithHTTPClient(client *http.Client) *GetStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get state params
func (o *GetStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccount adds the account to the get state params
func (o *GetStateParams) WithAccount(account string) *GetStateParams {
	o.SetAccount(account)
	return o
}

// SetAccount adds the account to the get state params
func (o *GetStateParams) SetAccount(account string) {
	o.Account = account
}

// WriteToRequest writes these params to a swagger request
func (o *GetStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account
	if err := r.SetPathParam("account", o.Account); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
