// Code generated by go-swagger; DO NOT EDIT.

package event_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/GoDieNow/TFT_Code/services/eventsengine/models"
)

// ListStatesReader is a Reader for the ListStates structure.
type ListStatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListStatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListStatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListStatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListStatesOK creates a ListStatesOK with default headers values
func NewListStatesOK() *ListStatesOK {
	return &ListStatesOK{}
}

/*ListStatesOK handles this case with default header values.

Description of a successfully operation
*/
type ListStatesOK struct {
	Payload []*models.MinimalState
}

func (o *ListStatesOK) Error() string {
	return fmt.Sprintf("[GET /event/status][%d] listStatesOK  %+v", 200, o.Payload)
}

func (o *ListStatesOK) GetPayload() []*models.MinimalState {
	return o.Payload
}

func (o *ListStatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListStatesInternalServerError creates a ListStatesInternalServerError with default headers values
func NewListStatesInternalServerError() *ListStatesInternalServerError {
	return &ListStatesInternalServerError{}
}

/*ListStatesInternalServerError handles this case with default header values.

Something unexpected happend, error raised
*/
type ListStatesInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *ListStatesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /event/status][%d] listStatesInternalServerError  %+v", 500, o.Payload)
}

func (o *ListStatesInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListStatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
