// Code generated by go-swagger; DO NOT EDIT.

package price_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSkuPriceParams creates a new GetSkuPriceParams object
// with the default values initialized.
func NewGetSkuPriceParams() *GetSkuPriceParams {
	var ()
	return &GetSkuPriceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSkuPriceParamsWithTimeout creates a new GetSkuPriceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSkuPriceParamsWithTimeout(timeout time.Duration) *GetSkuPriceParams {
	var ()
	return &GetSkuPriceParams{

		timeout: timeout,
	}
}

// NewGetSkuPriceParamsWithContext creates a new GetSkuPriceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSkuPriceParamsWithContext(ctx context.Context) *GetSkuPriceParams {
	var ()
	return &GetSkuPriceParams{

		Context: ctx,
	}
}

// NewGetSkuPriceParamsWithHTTPClient creates a new GetSkuPriceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSkuPriceParamsWithHTTPClient(client *http.Client) *GetSkuPriceParams {
	var ()
	return &GetSkuPriceParams{
		HTTPClient: client,
	}
}

/*GetSkuPriceParams contains all the parameters to send to the API endpoint
for the get sku price operation typically these are written to a http.Request
*/
type GetSkuPriceParams struct {

	/*ID
	  Id of sku price to be obtained

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sku price params
func (o *GetSkuPriceParams) WithTimeout(timeout time.Duration) *GetSkuPriceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sku price params
func (o *GetSkuPriceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sku price params
func (o *GetSkuPriceParams) WithContext(ctx context.Context) *GetSkuPriceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sku price params
func (o *GetSkuPriceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sku price params
func (o *GetSkuPriceParams) WithHTTPClient(client *http.Client) *GetSkuPriceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sku price params
func (o *GetSkuPriceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get sku price params
func (o *GetSkuPriceParams) WithID(id string) *GetSkuPriceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get sku price params
func (o *GetSkuPriceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSkuPriceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
