// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Plan Manager Management API
//
//  An API which supports creation, deletion, listing etc of Plan Manager
//  Schemes:
//    http
//    https
//  Host: localhost:8000
//  BasePath: /api/v1.0
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <sean@cyclops-labs.io>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
