// Code generated by go-swagger; DO NOT EDIT.

package sku_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateSkuHandlerFunc turns a function with the right signature into a create sku handler
type CreateSkuHandlerFunc func(CreateSkuParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateSkuHandlerFunc) Handle(params CreateSkuParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateSkuHandler interface for that can handle valid create sku params
type CreateSkuHandler interface {
	Handle(CreateSkuParams, interface{}) middleware.Responder
}

// NewCreateSku creates a new http.Handler for the create sku operation
func NewCreateSku(ctx *middleware.Context, handler CreateSkuHandler) *CreateSku {
	return &CreateSku{Context: ctx, Handler: handler}
}

/*CreateSku swagger:route POST /sku skuManagement createSku

create SKU

Creates a new sku

*/
type CreateSku struct {
	Context *middleware.Context
	Handler CreateSkuHandler
}

func (o *CreateSku) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateSkuParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
