// Code generated by go-swagger; DO NOT EDIT.

package sku_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSkuHandlerFunc turns a function with the right signature into a get sku handler
type GetSkuHandlerFunc func(GetSkuParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSkuHandlerFunc) Handle(params GetSkuParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSkuHandler interface for that can handle valid get sku params
type GetSkuHandler interface {
	Handle(GetSkuParams, interface{}) middleware.Responder
}

// NewGetSku creates a new http.Handler for the get sku operation
func NewGetSku(ctx *middleware.Context, handler GetSkuHandler) *GetSku {
	return &GetSku{Context: ctx, Handler: handler}
}

/*GetSku swagger:route GET /sku/{id} skuManagement getSku

Get specific sku

get sku with given skuid

*/
type GetSku struct {
	Context *middleware.Context
	Handler GetSkuHandler
}

func (o *GetSku) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSkuParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
