// Code generated by go-swagger; DO NOT EDIT.

package sku_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/GoDieNow/TFT_Code/services/planmanager/models"
)

// UpdateSkuOKCode is the HTTP code returned for type UpdateSkuOK
const UpdateSkuOKCode int = 200

/*UpdateSkuOK updated sku

swagger:response updateSkuOK
*/
type UpdateSkuOK struct {

	/*
	  In: Body
	*/
	Payload *models.Sku `json:"body,omitempty"`
}

// NewUpdateSkuOK creates UpdateSkuOK with default headers values
func NewUpdateSkuOK() *UpdateSkuOK {

	return &UpdateSkuOK{}
}

// WithPayload adds the payload to the update sku o k response
func (o *UpdateSkuOK) WithPayload(payload *models.Sku) *UpdateSkuOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update sku o k response
func (o *UpdateSkuOK) SetPayload(payload *models.Sku) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSkuOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSkuNotFoundCode is the HTTP code returned for type UpdateSkuNotFound
const UpdateSkuNotFoundCode int = 404

/*UpdateSkuNotFound sku with skuid not found

swagger:response updateSkuNotFound
*/
type UpdateSkuNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdateSkuNotFound creates UpdateSkuNotFound with default headers values
func NewUpdateSkuNotFound() *UpdateSkuNotFound {

	return &UpdateSkuNotFound{}
}

// WithPayload adds the payload to the update sku not found response
func (o *UpdateSkuNotFound) WithPayload(payload *models.ErrorResponse) *UpdateSkuNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update sku not found response
func (o *UpdateSkuNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSkuNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSkuInternalServerErrorCode is the HTTP code returned for type UpdateSkuInternalServerError
const UpdateSkuInternalServerErrorCode int = 500

/*UpdateSkuInternalServerError unexpected error

swagger:response updateSkuInternalServerError
*/
type UpdateSkuInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdateSkuInternalServerError creates UpdateSkuInternalServerError with default headers values
func NewUpdateSkuInternalServerError() *UpdateSkuInternalServerError {

	return &UpdateSkuInternalServerError{}
}

// WithPayload adds the payload to the update sku internal server error response
func (o *UpdateSkuInternalServerError) WithPayload(payload *models.ErrorResponse) *UpdateSkuInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update sku internal server error response
func (o *UpdateSkuInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSkuInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
