// Code generated by go-swagger; DO NOT EDIT.

package bundle_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListSkuBundlesHandlerFunc turns a function with the right signature into a list sku bundles handler
type ListSkuBundlesHandlerFunc func(ListSkuBundlesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListSkuBundlesHandlerFunc) Handle(params ListSkuBundlesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListSkuBundlesHandler interface for that can handle valid list sku bundles params
type ListSkuBundlesHandler interface {
	Handle(ListSkuBundlesParams, interface{}) middleware.Responder
}

// NewListSkuBundles creates a new http.Handler for the list sku bundles operation
func NewListSkuBundles(ctx *middleware.Context, handler ListSkuBundlesHandler) *ListSkuBundles {
	return &ListSkuBundles{Context: ctx, Handler: handler}
}

/*ListSkuBundles swagger:route GET /sku/bundle bundleManagement listSkuBundles

list SKU Bundles

lists all sku bundles

*/
type ListSkuBundles struct {
	Context *middleware.Context
	Handler ListSkuBundlesHandler
}

func (o *ListSkuBundles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListSkuBundlesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
