// Code generated by go-swagger; DO NOT EDIT.

package invoice_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/GoDieNow/TFT_Code/services/billing/models"
)

// GetInvoicesByResellerReader is a Reader for the GetInvoicesByReseller structure.
type GetInvoicesByResellerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInvoicesByResellerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInvoicesByResellerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetInvoicesByResellerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetInvoicesByResellerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetInvoicesByResellerOK creates a GetInvoicesByResellerOK with default headers values
func NewGetInvoicesByResellerOK() *GetInvoicesByResellerOK {
	return &GetInvoicesByResellerOK{}
}

/*GetInvoicesByResellerOK handles this case with default header values.

Description of a successfully operation
*/
type GetInvoicesByResellerOK struct {
	Payload []*models.Invoice
}

func (o *GetInvoicesByResellerOK) Error() string {
	return fmt.Sprintf("[GET /invoice/reseller/{id}][%d] getInvoicesByResellerOK  %+v", 200, o.Payload)
}

func (o *GetInvoicesByResellerOK) GetPayload() []*models.Invoice {
	return o.Payload
}

func (o *GetInvoicesByResellerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInvoicesByResellerNotFound creates a GetInvoicesByResellerNotFound with default headers values
func NewGetInvoicesByResellerNotFound() *GetInvoicesByResellerNotFound {
	return &GetInvoicesByResellerNotFound{}
}

/*GetInvoicesByResellerNotFound handles this case with default header values.

The invoice id provided doesn't exist
*/
type GetInvoicesByResellerNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetInvoicesByResellerNotFound) Error() string {
	return fmt.Sprintf("[GET /invoice/reseller/{id}][%d] getInvoicesByResellerNotFound  %+v", 404, o.Payload)
}

func (o *GetInvoicesByResellerNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetInvoicesByResellerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInvoicesByResellerInternalServerError creates a GetInvoicesByResellerInternalServerError with default headers values
func NewGetInvoicesByResellerInternalServerError() *GetInvoicesByResellerInternalServerError {
	return &GetInvoicesByResellerInternalServerError{}
}

/*GetInvoicesByResellerInternalServerError handles this case with default header values.

Something unexpected happend, error raised
*/
type GetInvoicesByResellerInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetInvoicesByResellerInternalServerError) Error() string {
	return fmt.Sprintf("[GET /invoice/reseller/{id}][%d] getInvoicesByResellerInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInvoicesByResellerInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetInvoicesByResellerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
