// Code generated by go-swagger; DO NOT EDIT.

package customer_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/GoDieNow/TFT_Code/services/customerdb/models"
)

// UpdateCustomerOKCode is the HTTP code returned for type UpdateCustomerOK
const UpdateCustomerOKCode int = 200

/*UpdateCustomerOK Customer with the given id was updated

swagger:response updateCustomerOK
*/
type UpdateCustomerOK struct {

	/*
	  In: Body
	*/
	Payload *models.ItemCreatedResponse `json:"body,omitempty"`
}

// NewUpdateCustomerOK creates UpdateCustomerOK with default headers values
func NewUpdateCustomerOK() *UpdateCustomerOK {

	return &UpdateCustomerOK{}
}

// WithPayload adds the payload to the update customer o k response
func (o *UpdateCustomerOK) WithPayload(payload *models.ItemCreatedResponse) *UpdateCustomerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update customer o k response
func (o *UpdateCustomerOK) SetPayload(payload *models.ItemCreatedResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCustomerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCustomerAcceptedCode is the HTTP code returned for type UpdateCustomerAccepted
const UpdateCustomerAcceptedCode int = 202

/*UpdateCustomerAccepted The customer was updated but there might have been some fails when adding part of the data

swagger:response updateCustomerAccepted
*/
type UpdateCustomerAccepted struct {

	/*
	  In: Body
	*/
	Payload *models.ItemCreatedResponse `json:"body,omitempty"`
}

// NewUpdateCustomerAccepted creates UpdateCustomerAccepted with default headers values
func NewUpdateCustomerAccepted() *UpdateCustomerAccepted {

	return &UpdateCustomerAccepted{}
}

// WithPayload adds the payload to the update customer accepted response
func (o *UpdateCustomerAccepted) WithPayload(payload *models.ItemCreatedResponse) *UpdateCustomerAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update customer accepted response
func (o *UpdateCustomerAccepted) SetPayload(payload *models.ItemCreatedResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCustomerAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCustomerNotFoundCode is the HTTP code returned for type UpdateCustomerNotFound
const UpdateCustomerNotFoundCode int = 404

/*UpdateCustomerNotFound The customer with the given id wasn't found

swagger:response updateCustomerNotFound
*/
type UpdateCustomerNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdateCustomerNotFound creates UpdateCustomerNotFound with default headers values
func NewUpdateCustomerNotFound() *UpdateCustomerNotFound {

	return &UpdateCustomerNotFound{}
}

// WithPayload adds the payload to the update customer not found response
func (o *UpdateCustomerNotFound) WithPayload(payload *models.ErrorResponse) *UpdateCustomerNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update customer not found response
func (o *UpdateCustomerNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCustomerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCustomerInternalServerErrorCode is the HTTP code returned for type UpdateCustomerInternalServerError
const UpdateCustomerInternalServerErrorCode int = 500

/*UpdateCustomerInternalServerError Something unexpected happend, error raised

swagger:response updateCustomerInternalServerError
*/
type UpdateCustomerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdateCustomerInternalServerError creates UpdateCustomerInternalServerError with default headers values
func NewUpdateCustomerInternalServerError() *UpdateCustomerInternalServerError {

	return &UpdateCustomerInternalServerError{}
}

// WithPayload adds the payload to the update customer internal server error response
func (o *UpdateCustomerInternalServerError) WithPayload(payload *models.ErrorResponse) *UpdateCustomerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update customer internal server error response
func (o *UpdateCustomerInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCustomerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
