// Code generated by go-swagger; DO NOT EDIT.

package price_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/GoDieNow/TFT_Code/services/planmanager/models"
)

// ListSkuPricesOKCode is the HTTP code returned for type ListSkuPricesOK
const ListSkuPricesOKCode int = 200

/*ListSkuPricesOK list of skus prices returned

swagger:response listSkuPricesOK
*/
type ListSkuPricesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.SkuPrice `json:"body,omitempty"`
}

// NewListSkuPricesOK creates ListSkuPricesOK with default headers values
func NewListSkuPricesOK() *ListSkuPricesOK {

	return &ListSkuPricesOK{}
}

// WithPayload adds the payload to the list sku prices o k response
func (o *ListSkuPricesOK) WithPayload(payload []*models.SkuPrice) *ListSkuPricesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list sku prices o k response
func (o *ListSkuPricesOK) SetPayload(payload []*models.SkuPrice) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSkuPricesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.SkuPrice, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListSkuPricesInternalServerErrorCode is the HTTP code returned for type ListSkuPricesInternalServerError
const ListSkuPricesInternalServerErrorCode int = 500

/*ListSkuPricesInternalServerError unexpected error

swagger:response listSkuPricesInternalServerError
*/
type ListSkuPricesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewListSkuPricesInternalServerError creates ListSkuPricesInternalServerError with default headers values
func NewListSkuPricesInternalServerError() *ListSkuPricesInternalServerError {

	return &ListSkuPricesInternalServerError{}
}

// WithPayload adds the payload to the list sku prices internal server error response
func (o *ListSkuPricesInternalServerError) WithPayload(payload *models.ErrorResponse) *ListSkuPricesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list sku prices internal server error response
func (o *ListSkuPricesInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSkuPricesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
