// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"gitlab.com/cyclops-utilities/datamodels"
)

// CDRReport c d r report
//
// swagger:model CDRReport
type CDRReport struct {

	// cost
	Cost datamodels.JSONdb `json:"Cost,omitempty" gorm:"type:jsonb"`

	// metadata
	Metadata datamodels.JSONdb `json:"Metadata,omitempty" gorm:"type:jsonb"`

	// resource Id
	ResourceID string `json:"ResourceId,omitempty"`

	// resource name
	ResourceName string `json:"ResourceName,omitempty"`

	// resource type
	ResourceType string `json:"ResourceType,omitempty"`

	// unit
	Unit string `json:"Unit,omitempty"`

	// usage breakup
	UsageBreakup datamodels.JSONdb `json:"UsageBreakup,omitempty" gorm:"type:jsonb"`
}

// Validate validates this c d r report
func (m *CDRReport) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CDRReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CDRReport) UnmarshalBinary(b []byte) error {
	var res CDRReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
