// Code generated by go-swagger; DO NOT EDIT.

package usage_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/GoDieNow/TFT_Code/services/udr/models"
)

// GetSystemUsageOKCode is the HTTP code returned for type GetSystemUsageOK
const GetSystemUsageOKCode int = 200

/*GetSystemUsageOK Description of a successfully operation

swagger:response getSystemUsageOK
*/
type GetSystemUsageOK struct {

	/*
	  In: Body
	*/
	Payload []*models.UReport `json:"body,omitempty"`
}

// NewGetSystemUsageOK creates GetSystemUsageOK with default headers values
func NewGetSystemUsageOK() *GetSystemUsageOK {

	return &GetSystemUsageOK{}
}

// WithPayload adds the payload to the get system usage o k response
func (o *GetSystemUsageOK) WithPayload(payload []*models.UReport) *GetSystemUsageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get system usage o k response
func (o *GetSystemUsageOK) SetPayload(payload []*models.UReport) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSystemUsageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.UReport, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetSystemUsageInternalServerErrorCode is the HTTP code returned for type GetSystemUsageInternalServerError
const GetSystemUsageInternalServerErrorCode int = 500

/*GetSystemUsageInternalServerError Something unexpected happend, error raised

swagger:response getSystemUsageInternalServerError
*/
type GetSystemUsageInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetSystemUsageInternalServerError creates GetSystemUsageInternalServerError with default headers values
func NewGetSystemUsageInternalServerError() *GetSystemUsageInternalServerError {

	return &GetSystemUsageInternalServerError{}
}

// WithPayload adds the payload to the get system usage internal server error response
func (o *GetSystemUsageInternalServerError) WithPayload(payload *models.ErrorResponse) *GetSystemUsageInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get system usage internal server error response
func (o *GetSystemUsageInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSystemUsageInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
