// Code generated by go-swagger; DO NOT EDIT.

package bulk_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBillRunParams creates a new GetBillRunParams object
// with the default values initialized.
func NewGetBillRunParams() *GetBillRunParams {
	var ()
	return &GetBillRunParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBillRunParamsWithTimeout creates a new GetBillRunParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBillRunParamsWithTimeout(timeout time.Duration) *GetBillRunParams {
	var ()
	return &GetBillRunParams{

		timeout: timeout,
	}
}

// NewGetBillRunParamsWithContext creates a new GetBillRunParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBillRunParamsWithContext(ctx context.Context) *GetBillRunParams {
	var ()
	return &GetBillRunParams{

		Context: ctx,
	}
}

// NewGetBillRunParamsWithHTTPClient creates a new GetBillRunParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBillRunParamsWithHTTPClient(client *http.Client) *GetBillRunParams {
	var ()
	return &GetBillRunParams{
		HTTPClient: client,
	}
}

/*GetBillRunParams contains all the parameters to send to the API endpoint
for the get bill run operation typically these are written to a http.Request
*/
type GetBillRunParams struct {

	/*ID
	  Id of the invoice to be checked

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get bill run params
func (o *GetBillRunParams) WithTimeout(timeout time.Duration) *GetBillRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bill run params
func (o *GetBillRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bill run params
func (o *GetBillRunParams) WithContext(ctx context.Context) *GetBillRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bill run params
func (o *GetBillRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bill run params
func (o *GetBillRunParams) WithHTTPClient(client *http.Client) *GetBillRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bill run params
func (o *GetBillRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get bill run params
func (o *GetBillRunParams) WithID(id strfmt.UUID) *GetBillRunParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get bill run params
func (o *GetBillRunParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBillRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
